### ISSUE TITLE
Dataset is not provided

### ISSUE THREAD

**Issue by Bitsy-Chuck** [ana-rlopez/cough_classification#7]
The data folder should have other content as well. Please provide a way to run the code.

**Comment by ana-rlopez** [comment]
This repository is meant for people to use on their own data, rather than using the data I employed in my experiments. Unfortunately, I haven't made that clear yet in the README.md file (I will do in a next commit). The data I used is from scrapped Youtube videos, and I am not sure if for licensing reasons I can provide that, but I will provide the csv list of the videos I used in a next commit. However, note that I hand-edited those recordings for the experiments, so I cannot promise the pre-processing in the repository will work adequately with the raw recordings.

**Comment by Bitsy-Chuck** [comment]
@ana-rlopez you don't actually need to provide the dataset... I wanted to say that the instruction for running were incorrect.
